apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: k8s-argo-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  description: Argo CD project for Rajesh0488/Kubernet-ArgoCD

  sourceRepos:
    - https://github.com/Rajesh0488/Kubernet-ArgoCD.git


  destinations:
    - namespace: k8s-argo-demo
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace